version: "2.4"
services:
  mitmproxy:
    image: "ghcr.io/skyfmmf/mobile-intercept:0.1.0"
    #build: .
    privileged: true
    ports:
      - "${EXT_IP}:${EXT_PORT}:${EXT_PORT}/udp"
    env_file:
      - ".env"
    volumes:
      - "./share:/share"
    init: true
    command: ["sleep", "infinity"]
